name: adwaita_icons
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/galonsos

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0

flutter:
  assets:
    - assets/icons/
